<a href="https://colab.research.google.com/github/eLio-yu/Computational-Mathematics/blob/main/Workshop_(Week_6).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Workshop (Week 6)**

Gaurav Poudel
University ID: 2607718

(Part 1)
Ndarray Creation & Manipulation

Problem 1

In [1]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print("Matrix A:\n", A)
print("Shape:", A.shape)
print("Dimension:", A.ndim)
print("Data type:", A.dtype)
print("Size:", A.size)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimension: 2
Data type: int64
Size: 9


Problem 2

In [6]:
import numpy as np

arr = 3 * np.ones((4,5), dtype = float)

print("Array = ")
print(arr)
print("Shape = ", arr.shape)
print("DataType = ", arr.dtype)

Array = 
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape =  (4, 5)
DataType =  float64


Problem 3

In [7]:
import numpy as np

arr = np.full((4,5), 3.0)

print("Array = ")
print(arr)
print("Shape = ", arr.shape)
print("DataType = ", arr.dtype)

Array = 
[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]
Shape =  (4, 5)
DataType =  float64


Problem 4

In [10]:
import numpy as np

arr = np.fromfunction(lambda i, j: np.abs(i+1-3*(j+1))/2, (3,3), dtype=int)

print(arr)
print(arr.shape)
print(arr.dtype)

[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]
(3, 3)
float64


Problem 5

In [11]:
import numpy as np

arr = np.diag([1,2,3,4], k=0)

print(arr)
print(arr.shape)
print(arr.dtype)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)
int64


Problem 6

In [13]:
import numpy as np

arr = np.random.randint(0,20,(4,5))
print(arr)
new_arr = arr[:3, :3]
print(new_arr)

[[ 2  3  8 12 17]
 [ 0  8 19  9 16]
 [ 0  6  5  8 10]
 [10 12 14 12  4]]
[[ 2  3  8]
 [ 0  8 19]
 [ 0  6  5]]


(Part 2)
Matrix Operations

Problem 1

In [14]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
B = np.array([[1,1,1],
              [2,2,2]])
C = A + B
print(C)

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

Problem 2

In [15]:
import numpy as np
def dot_product(vect1, vect2):
  vect1 = vect1.flatten()
  vect2 = vect2.flatten()
  return np.sum(np.multiply(vect1,vect2))
def matrix_vector_product(mat,vec):
  m,n = mat.shape
  p,q = vec.shape

  assert n==p, "the matrix and vector are not compatible for multiplication"

  result = np.zeros((m,q),dtype=float)

  for i in range(m):
    result[i] = dot_product(mat[i,:],vec)
  return result

mat1 = np.full((3,3), 3, dtype=int)
vec1 = np.full((3,1), 2, dtype=int)
print(mat1)
print(vec1)
result1 = matrix_vector_product(mat1,vec1)
print(result1)
result2 = mat1 @ vec1
print(result2)

[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[2]
 [2]
 [2]]
[[18.]
 [18.]
 [18.]]
[[18]
 [18]
 [18]]


Problem 3

In [16]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[3,4]])
C = np.dot(A,B)

print(C)

[[ 7 10]
 [15 22]]


Problem 4

In [17]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
if(A.T == A).all():
    print("Symmetric")
else:
    print("Not Symmetric")


Not Symmetric
